# Generated by Django 5.0.9 on 2026-10-09 05:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminpanel", "0001_initial"),
        ("cards", "0003_card_blocking"),
        ("transactions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="adminactionlog",
            name="changes",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="adminactionlog",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="adminactionlog",
            name="role",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="adminactionlog",
            name="target_id",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="adminactionlog",
            name="target_type",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.CreateModel(
            name="FraudLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rule",
                    models.CharField(
                        choices=[
                            (
                                "HIGH_VALUE_BURST",
                                "Multiple high-value transactions in a short time",
                            ),
                            (
                                "MULTI_SOURCE",
                                "Rapid transactions from different devices or locations",
                            ),
                        ],
                        max_length=30,
                    ),
                ),
                ("severity", models.CharField(default="MEDIUM", max_length=10)),
                ("details", models.TextField(blank=True, default="")),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "device_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("reviewed", models.BooleanField(db_index=True, default=False)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "resolution",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CONFIRMED_FRAUD", "Confirmed fraud"),
                            ("FALSE_POSITIVE", "False positive"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "review_note",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "card",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fraud_logs",
                        to="cards.card",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fraud_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fraud_logs",
                        to="transactions.transaction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fraud_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="RequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service", models.CharField(max_length=10)),
                ("method", models.CharField(max_length=8)),
                ("path", models.CharField(max_length=200)),
                ("status_code", models.PositiveSmallIntegerField()),
                ("duration_ms", models.PositiveIntegerField()),
                ("error", models.CharField(blank=True, default="", max_length=255)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["service", "created_at"],
                        name="adminpanel__service_38b3bd_idx",
                    )
                ],
            },
        ),
    ]