from django.conf import settings
from django.db import models


class Transaction(models.Model):
    """
    Rows in this table are created and resolved by the FastAPI payment
    service (fastapi_backend/payments.py) — Django never writes here, only
    reads (history, filtering, CSV export, admin panel, daily summary).
    FastAPI mirrors this exact table (see fastapi_backend/models.py); if
    you change a column here, update that mirror to match.
    """

    class Status(models.TextChoices):
        PENDING = "PENDING", "Pending"
        SUCCESS = "SUCCESS", "Success"
        FAILED = "FAILED", "Failed"

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="transactions")
    card = models.ForeignKey("cards.Card", on_delete=models.SET_NULL, null=True, blank=True, related_name="transactions")
    amount = models.DecimalField(max_digits=12, decimal_places=2)
    currency = models.CharField(max_length=3, default="USD")
    status = models.CharField(max_length=10, choices=Status.choices, default=Status.PENDING)
    reference = models.CharField(max_length=36, unique=True)  # UUID4 hex, generated by FastAPI
    failure_reason = models.CharField(max_length=255, blank=True, default="")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_at"]
        indexes = [
            models.Index(fields=["user", "status"]),
            models.Index(fields=["created_at"]),
        ]

    def __str__(self):
        return f"{self.reference} — {self.status} — {self.amount} {self.currency}"
