from django.conf import settings
from django.db import models


class Transaction(models.Model):
    """
    Rows in this table are created and resolved by the FastAPI payment
    service (fastapi_backend/payments.py) — Django never writes here, only
    reads (history, filtering, CSV export, admin panel, daily summary).
    FastAPI mirrors this exact table (see fastapi_backend/models.py); if
    you change a column here, update that mirror to match.
    """

    class Status(models.TextChoices):
        PENDING = "PENDING", "Pending"
        SUCCESS = "SUCCESS", "Success"
        FAILED = "FAILED", "Failed"

    class Category(models.TextChoices):
        SHOPPING = "SHOPPING", "Shopping"
        FOOD = "FOOD", "Food & dining"
        TRAVEL = "TRAVEL", "Travel"
        BILLS = "BILLS", "Bills & utilities"
        ENTERTAINMENT = "ENTERTAINMENT", "Entertainment"
        HEALTH = "HEALTH", "Health"
        OTHER = "OTHER", "Other"

    class FraudStatus(models.TextChoices):
        CLEAN = "CLEAN", "Clean"
        FLAGGED = "FLAGGED", "Flagged"
        CLEARED = "CLEARED", "Cleared after review"
        CONFIRMED = "CONFIRMED", "Confirmed fraud"

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="transactions")
    card = models.ForeignKey("cards.Card", on_delete=models.SET_NULL, null=True, blank=True, related_name="transactions")
    amount = models.DecimalField(max_digits=12, decimal_places=2)
    currency = models.CharField(max_length=3, default="USD")
    status = models.CharField(max_length=10, choices=Status.choices, default=Status.PENDING)
    reference = models.CharField(max_length=36, unique=True)  # UUID4 hex, generated by FastAPI
    failure_reason = models.CharField(max_length=255, blank=True, default="")
    category = models.CharField(max_length=20, choices=Category.choices, default=Category.OTHER)
    fraud_status = models.CharField(max_length=10, choices=FraudStatus.choices, default=FraudStatus.CLEAN)
    ip_address = models.GenericIPAddressField(null=True, blank=True)  # set by the payment service
    device_hash = models.CharField(max_length=64, blank=True, default="")  # hashed device id, never raw
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_at"]
        indexes = [
            models.Index(fields=["user", "status"]),
            models.Index(fields=["created_at"]),
            # Added for search / analytics on large tables:
            models.Index(fields=["user", "created_at"], name="txn_user_created_idx"),
            models.Index(fields=["status", "created_at"], name="txn_status_created_idx"),
            models.Index(fields=["card", "created_at"], name="txn_card_created_idx"),
            models.Index(fields=["amount"], name="txn_amount_idx"),
            models.Index(fields=["category"], name="txn_category_idx"),
            models.Index(fields=["fraud_status"], name="txn_fraud_status_idx"),
        ]

    def __str__(self):
        return f"{self.reference} — {self.status} — {self.amount} {self.currency}"
