# Generated by Django 5.0.9 on 2026-10-09 05:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0003_card_blocking"),
        ("transactions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="category",
            field=models.CharField(
                choices=[
                    ("SHOPPING", "Shopping"),
                    ("FOOD", "Food & dining"),
                    ("TRAVEL", "Travel"),
                    ("BILLS", "Bills & utilities"),
                    ("ENTERTAINMENT", "Entertainment"),
                    ("HEALTH", "Health"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="device_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="transaction",
            name="fraud_status",
            field=models.CharField(
                choices=[
                    ("CLEAN", "Clean"),
                    ("FLAGGED", "Flagged"),
                    ("CLEARED", "Cleared after review"),
                    ("CONFIRMED", "Confirmed fraud"),
                ],
                default="CLEAN",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["user", "created_at"], name="txn_user_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["status", "created_at"], name="txn_status_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["card", "created_at"], name="txn_card_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["amount"], name="txn_amount_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["category"], name="txn_category_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["fraud_status"], name="txn_fraud_status_idx"),
        ),
    ]